/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.papamitra.locationalarm;

public final class R {
    public static final class array {
        public static final int min_list_entries=0x7f060000;
        public static final int min_list_entryvalues=0x7f060001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int app_icon=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f090003;
        public static final int LinearLayout02=0x7f090004;
        public static final int TextView01=0x7f090009;
        public static final int alarm_cancel=0x7f09000f;
        public static final int alarm_save=0x7f09000e;
        public static final int alertTitle=0x7f090000;
        public static final int clockView=0x7f090001;
        public static final int dismiss=0x7f090002;
        public static final int empty=0x7f09000a;
        public static final int list=0x7f090008;
        public static final int list_address=0x7f090006;
        public static final int list_enabled=0x7f090007;
        public static final int list_label=0x7f090005;
        public static final int map_cancel=0x7f09000d;
        public static final int map_ok=0x7f09000c;
        public static final int mapview=0x7f09000b;
    }
    public static final class layout {
        public static final int alarm_alert=0x7f030000;
        public static final int list_row=0x7f030001;
        public static final int main=0x7f030002;
        public static final int map=0x7f030003;
        public static final int save_cancel_alarm=0x7f030004;
    }
    public static final class raw {
        public static final int fallbackring=0x7f050000;
        public static final int in_call_alarm=0x7f050001;
    }
    public static final class string {
        public static final int alarm_alert=0x7f07000c;
        public static final int alarm_alert_dismiss_text=0x7f07000b;
        public static final int app_name=0x7f070006;
        public static final int done=0x7f070009;
        public static final int label_pref=0x7f070005;
        public static final int location_picker=0x7f070002;
        public static final int location_pref=0x7f070004;
        public static final int map_cancel=0x7f070008;
        public static final int map_ok=0x7f070007;
        public static final int min_list_title=0x7f070000;
        public static final int revert=0x7f07000a;
        public static final int set_alarm=0x7f070003;
        public static final int start_time=0x7f070001;
    }
    public static final class style {
        /**  This theme is similar to the Theme.Dialog.Alert but does not rely on a
         non-public resource. 
         */
        public static final int alarm_alert=0x7f080001;
        public static final int clock=0x7f080000;
    }
    public static final class xml {
        public static final int preference=0x7f040000;
    }
}
